#! /bin/bash

system_info=$(uname -a)

if [[ "$system_info" == *"Darwin"* ]]; then
    ./tailwindcss -i ./styles/input.css -o ./styles/output.css --watch
elif [[ "$system_info" == *"Debian"* ]]; then    
    npx tailwindcss init
    
    npx tailwindcss -i ./styles/input.css -o ./styles/output.css --watch
else
    echo "Système d'exploitation non reconnu."
fi



